#!/bin/bash

set -e

USER_ON_SERVER="sdk-images"
SERVER="legacy.ubports.com"

DOWLOAD_JSON="com.ubuntu.sdkimage:released:download.json"
DATE_STAMP=`date +"%Y_%m_%d"`
IMAGE_PATH="public"
TEMP_PATH=`mktemp -d`

mkdir -p ${TEMP_PATH}/releases/xenial ${TEMP_PATH}/streams/v1/

if compgen -G "ubuntu-sdk-16.04-*.xz" > /dev/null; then
    cp ubuntu-sdk-16.04-*.xz ${TEMP_PATH}/releases/xenial
fi

cp *json ${TEMP_PATH}/streams/v1/
scp -rp ${TEMP_PATH}/* $USER_ON_SERVER@$SERVER:${IMAGE_PATH}
rm -r ${TEMP_PATH}
